# Generated by Django 5.0.4 on 2024-09-25 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dancestyle_studio_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('visits_amount', models.IntegerField(verbose_name='visits amount')),
            ],
        ),
        migrations.AlterField(
            model_name='dancestyle',
            name='description',
            field=models.TextField(max_length=300, verbose_name='description   '),
        ),
        migrations.AlterField(
            model_name='dancestyle',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date')),
                ('description', models.TextField()),
                ('max_people_count', models.IntegerField(verbose_name='max people count')),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dancestyle', verbose_name='dance style')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studio')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_amount', models.IntegerField(verbose_name='visits amount')),
                ('replenishment_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.replenishmenthistory', verbose_name='replenishment history')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
