# Generated by Django 5.0.4 on 2024-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_replenishmenthistory_alter_dancestyle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='visits_amount',
            field=models.IntegerField(default=0, verbose_name='visits amount'),
        ),
    ]
