# Generated by Django 5.0.4 on 2024-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscription_visits_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsignup',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
