# Generated by Django 5.0.4 on 2024-10-02 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_achievement_studentachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentachievement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
