# Generated by Django 5.0.4 on 2024-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('date', models.DateField(verbose_name='date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photos/', verbose_name='Photo')),
            ],
        ),
    ]
